# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_tv.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(377, 520)
        MainWindow.setMinimumSize(QtCore.QSize(377, 520))
        MainWindow.setMaximumSize(QtCore.QSize(377, 520))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setGeometry(QtCore.QRect(10, 30, 22, 171))
        self.volume_slider.setOrientation(QtCore.Qt.Vertical)
        self.volume_slider.setObjectName("volume_slider")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(130, 260, 121, 201))
        self.frame.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(65, 65, 65);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.volume_down_button = QtWidgets.QPushButton(self.frame)
        self.volume_down_button.setGeometry(QtCore.QRect(0, 100, 31, 31))
        self.volume_down_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.volume_down_button.setObjectName("volume_down_button")
        self.volume_up_button = QtWidgets.QPushButton(self.frame)
        self.volume_up_button.setGeometry(QtCore.QRect(0, 50, 31, 31))
        self.volume_up_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.volume_up_button.setObjectName("volume_up_button")
        self.mute_button = QtWidgets.QPushButton(self.frame)
        self.mute_button.setGeometry(QtCore.QRect(40, 80, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(14)
        self.mute_button.setFont(font)
        self.mute_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.mute_button.setObjectName("mute_button")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 80, 31, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 80, 31, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.channel_down_button = QtWidgets.QPushButton(self.frame)
        self.channel_down_button.setGeometry(QtCore.QRect(90, 100, 31, 31))
        self.channel_down_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.channel_down_button.setObjectName("channel_down_button")
        self.channel_up_button = QtWidgets.QPushButton(self.frame)
        self.channel_up_button.setGeometry(QtCore.QRect(90, 50, 31, 31))
        self.channel_up_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.channel_up_button.setObjectName("channel_up_button")
        self.power_button = QtWidgets.QPushButton(self.frame)
        self.power_button.setGeometry(QtCore.QRect(30, 10, 61, 21))
        self.power_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius: 3px;\n"
"\n"
"")
        self.power_button.setObjectName("power_button")
        self.netflix_button = QtWidgets.QPushButton(self.frame)
        self.netflix_button.setGeometry(QtCore.QRect(30, 140, 61, 16))
        self.netflix_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"border-radius: 3px;\n"
"")
        self.netflix_button.setObjectName("netflix_button")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 55, 16))
        self.label_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.volume_down_button.raise_()
        self.volume_up_button.raise_()
        self.mute_button.raise_()
        self.label_2.raise_()
        self.channel_down_button.raise_()
        self.channel_up_button.raise_()
        self.power_button.raise_()
        self.netflix_button.raise_()
        self.label_3.raise_()
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.tv_output = QtWidgets.QLabel(self.centralwidget)
        self.tv_output.setGeometry(QtCore.QRect(40, 10, 321, 221))
        self.tv_output.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.tv_output.setText("")
        self.tv_output.setScaledContents(True)
        self.tv_output.setObjectName("tv_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 377, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.volume_down_button.setText(_translate("MainWindow", "-"))
        self.volume_up_button.setText(_translate("MainWindow", "+"))
        self.mute_button.setText(_translate("MainWindow", "X"))
        self.label.setText(_translate("MainWindow", "VOL"))
        self.label_2.setText(_translate("MainWindow", "CH"))
        self.channel_down_button.setText(_translate("MainWindow", "-"))
        self.channel_up_button.setText(_translate("MainWindow", "+"))
        self.power_button.setText(_translate("MainWindow", "Power"))
        self.netflix_button.setText(_translate("MainWindow", "NETFLIX"))
        self.label_3.setText(_translate("MainWindow", "Javi TV"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
